
#ifndef __RAVPOWER_PMIC_H
#define __RAVPOWER_PMIC_H

#define RAVPOWER_PMIC_I2C_ADDRESS			0x0a

#define RAVPOWER_PMIC_DEVICE_STATUS_REG			0x01
#define RAVPOWER_PMIC_DEVICE_STATUS_LOW_TEMP_MASK		(1 << 2)
#define RAVPOWER_PMIC_DEVICE_STATUS_HIGH_TEMP_MASK		(1 << 3)
#define RAVPOWER_PMIC_DEVICE_STATUS_LOW_VOLTAGE_MASK		(1 << 5)
#define RAVPOWER_PMIC_DEVICE_STATUS_CHARGING_MASK		(1 << 6)
#define RAVPOWER_PMIC_DEVICE_STATUS_CHARGING(x)			((x) & RAVPOWER_PMIC_DEVICE_STATUS_CHARGING_MASK)			
#define RAVPOWER_PMIC_DEVICE_STATUS_SHUTDOWN_REQUEST_MASK	(1 << 7)

#define RAVPOWER_PMIC_CMD_SHUTDOWN_REG		        0x03

#define RAVPOWER_PMIC_BATTERY_VOLUME_REG		0x10
#define RAVPOWER_PMIC_BATTERY_VOLUME_MASK		0xFF

#define RAVPOWER_PMIC_CMD_POWER_LED_REG 		0x61

#endif
